---
# ====== Application: Gestión de Solicitudes =================
identification: 
  name: Gestión de Solicitudes
  alias: GESTIÓN-DE-SOLICITUDES
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 53717730544594905179

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_WILLIAMAPEX

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Gestión de Solicitudes

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 53717731367648905180

navigation-bar: 
  implementation: List
  list: Navigation Bar # 53717732510417905183
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 15630676653634

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Gestión de Solicitudes

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 53717726089296905176
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15630654747390

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 53717726388072905177
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 15630654747396

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 53717726687354905177
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 15630654747398

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 53717726932267905177
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 15630654747398

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 53717727202303905177
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 15630654747398

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 53717727507229905177
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 15630654747404

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 53717727816580905178
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 15630654747410

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 53717728106352905178
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 15630654747416

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 53717728413893905178
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15630654747416

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 53717728786228905178
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15630654747418

- # ====== Component Setting: NATIVE_IR ========================
  id: 53717729004084905178
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15630654747420

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 53717729324700905178
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15630654747423

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 53717729643560905179
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15630654747423

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 53717729938463905179
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 15630654747423

